# .goreleaser.yml
# GoReleaser configuration for Portunix

project_name: portunix

# Ať se snapshot NEoznačuje commitem (žádné -60b7fbf)
snapshot:
  name_template: "{{ .Version }}"

before:
  hooks:
    - go mod tidy

builds:
  - id: portunix
    binary: portunix
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
    ldflags:
      - -X main.version={{.Version}}
      - -s -w
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- tolower .Os }}_{{ .Arch }}"
    # Windows -> .zip, ostatní -> .tar.gz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: false
    files:
      - src: scripts/install.sh
        dst: install.sh
        strip_parent: true
        info:
          mode: 0755
      - src: scripts/install.ps1
        dst: install.ps1
        strip_parent: true
      - LICENSE*
      - README*
      # případně doplň např. shell completion:
      # - "completions/*"
 
dist: dist

checksum:
  name_template: "checksums_{{ .Version }}.txt"
  algorithm: sha256

release:
  github:
    owner: cassandragargoyle
    name: portunix
  
  # Create individual checksum files for each binary
  extra_files:
    - glob: ./dist/*
  
  # Release notes
  header: |
    ## Portunix {{.Version}}
    
    Universal development environment management tool.
  
  footer: |
    ## Installation
    
    Download and extract the appropriate archive for your platform, then run the installation script:
    
    ### Linux/macOS
    ```bash
    # Download and extract
    tar -xzf portunix_{{.Version}}_linux_amd64.tar.gz
    cd portunix_{{.Version}}_linux_amd64
    
    # Interactive installation
    ./install.sh
    
    # Or silent installation
    ./install.sh --silent --add-to-path
    ```
    
    ### Windows
    ```powershell
    # Download and extract
    Expand-Archive portunix_{{.Version}}_windows_amd64.zip
    cd portunix_{{.Version}}_windows_amd64
    
    # Interactive installation
    .\install.ps1
    
    # Or silent installation
    .\install.ps1 -Silent -AddToPath
    ```
    
    ## Self-Update
    
    Once installed, you can update Portunix using:
    ```bash
    portunix update
    ```

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'