#!/bin/bash
# Portunix Auto-Install Script (Linux)
# Generated by file-server.py
# Server: http://192.168.53.95:8080

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Configuration
SERVER_URL="http://192.168.53.95:8080"
INSTALL_DIR="/usr/local/bin"

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           Portunix Auto-Installer (Linux)                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

print_info "Downloading from: $SERVER_URL"
print_info "Installing to: $INSTALL_DIR"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "Please run as root (use sudo)"
    exit 1
fi

# Download main binary
print_info "Downloading Portunix main binary..."
if curl -fsSL -o "$INSTALL_DIR/portunix" "$SERVER_URL/portunix"; then
    chmod +x "$INSTALL_DIR/portunix"
    print_success "Portunix binary installed"
else
    print_error "Failed to download Portunix binary"
    exit 1
fi

# Download helpers
print_info "Downloading helper binaries..."

if curl -fsSL -o "$INSTALL_DIR/ptx-container" "$SERVER_URL/bin/ptx-container"; then
    chmod +x "$INSTALL_DIR/ptx-container"
    print_success "ptx-container installed"
else
    print_error "Failed to download ptx-container"
fi

if curl -fsSL -o "$INSTALL_DIR/portunix" "$SERVER_URL/bin/portunix"; then
    chmod +x "$INSTALL_DIR/portunix"
    print_success "portunix installed"
else
    print_error "Failed to download portunix"
fi

echo ""
print_success "Installation completed!"
echo ""
print_info "Verify installation:"
echo "  portunix --version"
echo ""
