# Portunix Auto-Install Script (Windows)
# Generated by file-server.py
# Server: http://192.168.53.95:8080

$ErrorActionPreference = "Stop"

# Configuration
$ServerUrl = "http://192.168.53.95:8080"
$InstallDir = "$env:ProgramFiles\Portunix"

Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════════════╗" -ForegroundColor Blue
Write-Host "║           Portunix Auto-Installer (Windows)                   ║" -ForegroundColor Blue
Write-Host "╚════════════════════════════════════════════════════════════════╝" -ForegroundColor Blue
Write-Host ""

Write-Host "ℹ️  Downloading from: $ServerUrl" -ForegroundColor Blue
Write-Host "ℹ️  Installing to: $InstallDir" -ForegroundColor Blue
Write-Host ""

# Check admin rights
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "❌ Please run as Administrator" -ForegroundColor Red
    exit 1
}

# Create install directory
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}

# Download main binary
Write-Host "ℹ️  Downloading Portunix main binary..." -ForegroundColor Blue
try {
    Invoke-WebRequest -Uri "$ServerUrl/portunix" -OutFile "$InstallDir\portunix.exe"
    Write-Host "✅ Portunix binary installed" -ForegroundColor Green
} catch {
    Write-Host "❌ Failed to download Portunix binary: $_" -ForegroundColor Red
    exit 1
}

# Download helpers
Write-Host "ℹ️  Downloading helper binaries..." -ForegroundColor Blue

try {
    Invoke-WebRequest -Uri "$ServerUrl/bin/ptx-container" -OutFile "$InstallDir\ptx-container.exe"
    Write-Host "✅ ptx-container installed" -ForegroundColor Green
} catch {
    Write-Host "❌ Failed to download ptx-container: $_" -ForegroundColor Red
}

try {
    Invoke-WebRequest -Uri "$ServerUrl/bin/portunix" -OutFile "$InstallDir\portunix.exe"
    Write-Host "✅ portunix installed" -ForegroundColor Green
} catch {
    Write-Host "❌ Failed to download portunix: $_" -ForegroundColor Red
}

# Add to PATH if not already there
$currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
if ($currentPath -notlike "*$InstallDir*") {
    Write-Host "ℹ️  Adding to system PATH..." -ForegroundColor Blue
    [Environment]::SetEnvironmentVariable("Path", "$currentPath;$InstallDir", "Machine")
    Write-Host "✅ Added to PATH" -ForegroundColor Green
    Write-Host "⚠️  Restart your terminal to use Portunix" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "✅ Installation completed!" -ForegroundColor Green
Write-Host ""
Write-Host "ℹ️  Verify installation (after restarting terminal):" -ForegroundColor Blue
Write-Host "  portunix --version"
Write-Host ""
