/*
 *  This file is part of CassandraGargoyle Community Project
 *  Licensed under the MIT License - see LICENSE file for details
 */
// Package scaffold writes the spec-kit-pm scaffold into a target project,
// honouring the split layout from ADR-040 D1: .specpm/ holds kit cache
// (regenerated by init / upgrade) while specs/project/<id>/ holds user
// artifacts (never overwritten).
package scaffold

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Options drives a scaffold write.
type Options struct {
	TargetDir string
	KitDir    string
	ProjectID string
	Force     bool
	// Refresh switches the call into upgrade mode (ADR-041 D3). Refreshed
	// kit subtrees (templates/, agents/, workflows/, profiles/, memory/,
	// scripts/) are wiped before re-materialising. Carve-outs (kit.json,
	// extensions/, presets/) are preserved. specs/project/ is never touched.
	// When Refresh is true, ProjectID is ignored.
	Refresh bool
}

// Result reports what changed.
type Result struct {
	WrittenKitFiles  int
	SkippedNoOp      bool
	CreatedArtifacts []string
	WipedSubtrees    []string
}

// kitSubtreesRefreshed lists .specpm/ subtrees that ADR-041 D3 marks as
// authoritatively refreshed by upgrade. Kept in one place so writer and tests
// can assert on it.
var kitSubtreesRefreshed = []string{"templates", "agents", "workflows", "profiles", "memory", "scripts"}

// Write installs the scaffold according to opts. It is idempotent: a second
// call with no kit changes is a no-op (Result.SkippedNoOp = true). User
// artifacts under specs/project/<id>/ are NEVER overwritten — at most a
// placeholder Charter is created on first run.
func Write(opts Options) (*Result, error) {
	if opts.TargetDir == "" {
		return nil, fmt.Errorf("scaffold: empty target dir")
	}
	if opts.KitDir == "" {
		return nil, fmt.Errorf("scaffold: empty kit dir")
	}

	res := &Result{}

	specpmRoot := filepath.Join(opts.TargetDir, ".specpm")

	// In Refresh mode (ADR-041 D3), wipe the kit subtrees first so files
	// removed upstream do not linger. Carve-outs (kit.json, extensions/,
	// presets/) are not in this list and so survive untouched.
	if opts.Refresh {
		for _, sub := range kitSubtreesRefreshed {
			path := filepath.Join(specpmRoot, sub)
			if err := os.RemoveAll(path); err != nil {
				return nil, fmt.Errorf("wipe %s: %w", sub, err)
			}
			res.WipedSubtrees = append(res.WipedSubtrees, sub)
		}
	}

	// 1. Refresh .specpm/ from kit. We mirror four upstream subtrees:
	//    templates/, agents/, workflows/, profiles/. The local-only memory/,
	//    scripts/, extensions/, presets/ folders are bootstrapped if absent.
	copyForce := opts.Force || opts.Refresh
	for _, sub := range []string{"templates", "agents", "workflows", "profiles"} {
		src := filepath.Join(opts.KitDir, sub)
		if _, err := os.Stat(src); err != nil {
			// Not all upstream subtrees may exist for every pinned ref.
			continue
		}
		dst := filepath.Join(specpmRoot, sub)
		written, err := copyTree(src, dst, copyForce)
		if err != nil {
			return nil, fmt.Errorf("copy %s: %w", sub, err)
		}
		res.WrittenKitFiles += written
	}
	for _, sub := range []string{"memory", "scripts", "extensions", "presets"} {
		if err := os.MkdirAll(filepath.Join(specpmRoot, sub), 0o755); err != nil {
			return nil, fmt.Errorf("mkdir %s: %w", sub, err)
		}
	}
	if err := writeIfMissing(filepath.Join(specpmRoot, "memory", "governance.md"), defaultGovernance); err != nil {
		return nil, err
	}

	// 2. Create per-project artifact placeholders. NEVER overwrite — even
	//    with --force, user content is sacred. In Refresh mode we skip this
	//    entirely (upgrade does not touch specs/project/).
	if !opts.Refresh {
		artifactDir := filepath.Join(opts.TargetDir, "specs", "project", opts.ProjectID)
		if err := os.MkdirAll(artifactDir, 0o755); err != nil {
			return nil, fmt.Errorf("mkdir artifacts: %w", err)
		}
		charterPath := filepath.Join(artifactDir, "project.md")
		if _, err := os.Stat(charterPath); os.IsNotExist(err) {
			// Materialise the upstream Charter template as a placeholder so the
			// PM agent's preflight has something to read on day one.
			tplPath := filepath.Join(opts.KitDir, "templates", "project", "charter.md")
			if data, terr := os.ReadFile(tplPath); terr == nil {
				if werr := os.WriteFile(charterPath, data, 0o644); werr != nil {
					return nil, fmt.Errorf("write Charter placeholder: %w", werr)
				}
				res.CreatedArtifacts = append(res.CreatedArtifacts, charterPath)
			} else {
				// No upstream template — drop a TODO stub so the dir is non-empty.
				if werr := os.WriteFile(charterPath, []byte(stubCharter(opts.ProjectID)), 0o644); werr != nil {
					return nil, fmt.Errorf("write Charter stub: %w", werr)
				}
				res.CreatedArtifacts = append(res.CreatedArtifacts, charterPath)
			}
		}
		for _, sub := range []string{"execution", "validation"} {
			if err := os.MkdirAll(filepath.Join(artifactDir, sub), 0o755); err != nil {
				return nil, fmt.Errorf("mkdir %s: %w", sub, err)
			}
		}
	}

	if res.WrittenKitFiles == 0 && len(res.CreatedArtifacts) == 0 && len(res.WipedSubtrees) == 0 {
		res.SkippedNoOp = true
	}
	return res, nil
}

// copyTree walks src and copies regular files into dst preserving the
// relative layout. Directories are created on demand. When force is false
// existing files are kept; when true they are overwritten. Returns the
// number of files actually written.
func copyTree(src, dst string, force bool) (int, error) {
	written := 0
	err := filepath.Walk(src, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		if !force {
			if _, err := os.Stat(target); err == nil {
				// Skip — same-content / divergent doesn't matter for the
				// kit cache, the user can --force to refresh.
				return nil
			}
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := copyFile(path, target); err != nil {
			return err
		}
		written++
		return nil
	})
	return written, err
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

func writeIfMissing(path, content string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func stubCharter(projectID string) string {
	return strings.ReplaceAll(charterStubTemplate, "{{PROJECT_ID}}", projectID)
}

const charterStubTemplate = `---
project_id: {{PROJECT_ID}}
status: draft
authoring_party: <<TO FILL>>
project_manager: <<TO FILL>>
sponsor: <<TO FILL>>
source_authority: <<TO FILL>>
created: <<TO FILL>>
updated: <<TO FILL>>
---

# Project Charter — {{PROJECT_ID}}

This file was scaffolded by 'ptx-specpm init'. Run /specpm.init in your AI
agent (Claude Code by default) to draft the Charter from your project
context. The PM agent's preflight will refuse to produce planning artifacts
until 'status: active' and a single named project_manager are recorded here.

See .specpm/templates/project/charter.md and .specpm/agents/pm.md for the
contract this Charter must satisfy.
`

const defaultGovernance = `# spec-kit-pm Governance Memory

This file is the long-lived PM context that AI agents read on every run. It
is included from your root CLAUDE.md (when --integration claude was used).

## Initiation gate

Per the spec-kit-pm convention, every project MUST pass the Initiation gate
before any planning artifact (plan, risks, decisions, KPIs, reports) is
produced. The gate produces a Charter at specs/project/<project-id>/project.md
with status: active.

## Active project IDs

<!-- Add one bullet per initiated project under specs/project/. -->

## Pointers

- Templates: .specpm/templates/
- Agent prompts: .specpm/agents/
- Workflows: .specpm/workflows/
- Profiles: .specpm/profiles/
`
