// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: src/helpers/ptx-trace/proto/fulltext.proto

package fulltext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IndexRequest represents a single document to index
type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Document ID (trace event ID)
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                                                             // Main searchable content
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata fields
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`                                                  // Content type (e.g., "trace_event")
	IndexName     string                 `protobuf:"bytes,5,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`                                                        // Target index name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{0}
}

func (x *IndexRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IndexRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IndexRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *IndexRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *IndexRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IndexResponse) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

// IndexBatchRequest for bulk indexing
type IndexBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*IndexRequest        `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexBatchRequest) Reset() {
	*x = IndexBatchRequest{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexBatchRequest) ProtoMessage() {}

func (x *IndexBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexBatchRequest.ProtoReflect.Descriptor instead.
func (*IndexBatchRequest) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{2}
}

func (x *IndexBatchRequest) GetDocuments() []*IndexRequest {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *IndexBatchRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type IndexBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IndexedCount  int32                  `protobuf:"varint,3,opt,name=indexed_count,json=indexedCount,proto3" json:"indexed_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	FailedIds     []string               `protobuf:"bytes,5,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexBatchResponse) Reset() {
	*x = IndexBatchResponse{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexBatchResponse) ProtoMessage() {}

func (x *IndexBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexBatchResponse.ProtoReflect.Descriptor instead.
func (*IndexBatchResponse) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{3}
}

func (x *IndexBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IndexBatchResponse) GetIndexedCount() int32 {
	if x != nil {
		return x.IndexedCount
	}
	return 0
}

func (x *IndexBatchResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *IndexBatchResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

// DeleteDocumentRequest removes a document from the index
type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteDocumentRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SearchRequest for querying the fulltext index
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                                                               // Search query
	IndexName     string                 `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`                                                      // Index to search
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                                                              // Max results (default: 10)
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                                                                            // Pagination offset
	Highlight     bool                   `protobuf:"varint,5,opt,name=highlight,proto3" json:"highlight,omitempty"`                                                                      // Enable highlighting
	Filters       map[string]string      `protobuf:"bytes,6,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Field filters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetHighlight() bool {
	if x != nil {
		return x.Highlight
	}
	return false
}

func (x *SearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Highlight     string                 `protobuf:"bytes,3,opt,name=highlight,proto3" json:"highlight,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetHighlight() string {
	if x != nil {
		return x.Highlight
	}
	return ""
}

func (x *SearchResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Results       []*SearchResult        `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	TotalHits     int64                  `protobuf:"varint,4,opt,name=total_hits,json=totalHits,proto3" json:"total_hits,omitempty"`
	TookMs        int64                  `protobuf:"varint,5,opt,name=took_ms,json=tookMs,proto3" json:"took_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalHits() int64 {
	if x != nil {
		return x.TotalHits
	}
	return 0
}

func (x *SearchResponse) GetTookMs() int64 {
	if x != nil {
		return x.TookMs
	}
	return 0
}

// GetStatsRequest for index statistics
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"` // Empty for all indices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{9}
}

func (x *GetStatsRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type GetStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DocumentCount  int64                  `protobuf:"varint,3,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	IndexSizeBytes int64                  `protobuf:"varint,4,opt,name=index_size_bytes,json=indexSizeBytes,proto3" json:"index_size_bytes,omitempty"`
	Indices        map[string]int64       `protobuf:"bytes,5,rep,name=indices,proto3" json:"indices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Per-index document counts
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetStatsResponse) GetDocumentCount() int64 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *GetStatsResponse) GetIndexSizeBytes() int64 {
	if x != nil {
		return x.IndexSizeBytes
	}
	return 0
}

func (x *GetStatsResponse) GetIndices() map[string]int64 {
	if x != nil {
		return x.Indices
	}
	return nil
}

// EnsureIndexRequest creates index if not exists
type EnsureIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Settings      map[string]string      `protobuf:"bytes,2,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Index settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureIndexRequest) Reset() {
	*x = EnsureIndexRequest{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureIndexRequest) ProtoMessage() {}

func (x *EnsureIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureIndexRequest.ProtoReflect.Descriptor instead.
func (*EnsureIndexRequest) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{11}
}

func (x *EnsureIndexRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *EnsureIndexRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type EnsureIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"` // True if newly created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureIndexResponse) Reset() {
	*x = EnsureIndexResponse{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureIndexResponse) ProtoMessage() {}

func (x *EnsureIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureIndexResponse.ProtoReflect.Descriptor instead.
func (*EnsureIndexResponse) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{12}
}

func (x *EnsureIndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnsureIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnsureIndexResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

// DeleteIndexRequest removes an entire index
type DeleteIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexRequest) Reset() {
	*x = DeleteIndexRequest{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexRequest) ProtoMessage() {}

func (x *DeleteIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexRequest.ProtoReflect.Descriptor instead.
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteIndexRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type DeleteIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIndexResponse) Reset() {
	*x = DeleteIndexResponse{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexResponse) ProtoMessage() {}

func (x *DeleteIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIndexResponse.ProtoReflect.Descriptor instead.
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteIndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthCheckRequest for service health
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{15}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"` // e.g., "elasticsearch", "lucene"
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_src_helpers_ptx_trace_proto_fulltext_proto protoreflect.FileDescriptor

const file_src_helpers_ptx_trace_proto_fulltext_proto_rawDesc = "" +
	"\n" +
	"*src/helpers/ptx-trace/proto/fulltext.proto\x12\x14portunix.fulltext.v1\"\x85\x02\n" +
	"\fIndexRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12L\n" +
	"\bmetadata\x18\x03 \x03(\v20.portunix.fulltext.v1.IndexRequest.MetadataEntryR\bmetadata\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"index_name\x18\x05 \x01(\tR\tindexName\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\rIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\"t\n" +
	"\x11IndexBatchRequest\x12@\n" +
	"\tdocuments\x18\x01 \x03(\v2\".portunix.fulltext.v1.IndexRequestR\tdocuments\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\"\xaf\x01\n" +
	"\x12IndexBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rindexed_count\x18\x03 \x01(\x05R\findexedCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\x05R\vfailedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x05 \x03(\tR\tfailedIds\"F\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\"L\n" +
	"\x16DeleteDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x98\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"index_name\x18\x02 \x01(\tR\tindexName\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x1c\n" +
	"\thighlight\x18\x05 \x01(\bR\thighlight\x12J\n" +
	"\afilters\x18\x06 \x03(\v20.portunix.fulltext.v1.SearchRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf7\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x1c\n" +
	"\thighlight\x18\x03 \x01(\tR\thighlight\x12L\n" +
	"\bmetadata\x18\x04 \x03(\v20.portunix.fulltext.v1.SearchResult.MetadataEntryR\bmetadata\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\x0eSearchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\aresults\x18\x03 \x03(\v2\".portunix.fulltext.v1.SearchResultR\aresults\x12\x1d\n" +
	"\n" +
	"total_hits\x18\x04 \x01(\x03R\ttotalHits\x12\x17\n" +
	"\atook_ms\x18\x05 \x01(\x03R\x06tookMs\"0\n" +
	"\x0fGetStatsRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\"\xa2\x02\n" +
	"\x10GetStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0edocument_count\x18\x03 \x01(\x03R\rdocumentCount\x12(\n" +
	"\x10index_size_bytes\x18\x04 \x01(\x03R\x0eindexSizeBytes\x12M\n" +
	"\aindices\x18\x05 \x03(\v23.portunix.fulltext.v1.GetStatsResponse.IndicesEntryR\aindices\x1a:\n" +
	"\fIndicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xc4\x01\n" +
	"\x12EnsureIndexRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12R\n" +
	"\bsettings\x18\x02 \x03(\v26.portunix.fulltext.v1.EnsureIndexRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x13EnsureIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\"3\n" +
	"\x12DeleteIndexRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\"I\n" +
	"\x13DeleteIndexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"\x95\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion2\x95\x06\n" +
	"\x0fFulltextService\x12X\n" +
	"\rIndexDocument\x12\".portunix.fulltext.v1.IndexRequest\x1a#.portunix.fulltext.v1.IndexResponse\x12_\n" +
	"\n" +
	"IndexBatch\x12'.portunix.fulltext.v1.IndexBatchRequest\x1a(.portunix.fulltext.v1.IndexBatchResponse\x12k\n" +
	"\x0eDeleteDocument\x12+.portunix.fulltext.v1.DeleteDocumentRequest\x1a,.portunix.fulltext.v1.DeleteDocumentResponse\x12S\n" +
	"\x06Search\x12#.portunix.fulltext.v1.SearchRequest\x1a$.portunix.fulltext.v1.SearchResponse\x12Y\n" +
	"\bGetStats\x12%.portunix.fulltext.v1.GetStatsRequest\x1a&.portunix.fulltext.v1.GetStatsResponse\x12b\n" +
	"\vEnsureIndex\x12(.portunix.fulltext.v1.EnsureIndexRequest\x1a).portunix.fulltext.v1.EnsureIndexResponse\x12b\n" +
	"\vDeleteIndex\x12(.portunix.fulltext.v1.DeleteIndexRequest\x1a).portunix.fulltext.v1.DeleteIndexResponse\x12b\n" +
	"\vHealthCheck\x12(.portunix.fulltext.v1.HealthCheckRequest\x1a).portunix.fulltext.v1.HealthCheckResponseB;Z9portunix.ai/portunix/src/helpers/ptx-trace/proto/fulltextb\x06proto3"

var (
	file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescOnce sync.Once
	file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescData []byte
)

func file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescGZIP() []byte {
	file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescOnce.Do(func() {
		file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_helpers_ptx_trace_proto_fulltext_proto_rawDesc), len(file_src_helpers_ptx_trace_proto_fulltext_proto_rawDesc)))
	})
	return file_src_helpers_ptx_trace_proto_fulltext_proto_rawDescData
}

var file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_src_helpers_ptx_trace_proto_fulltext_proto_goTypes = []any{
	(*IndexRequest)(nil),           // 0: portunix.fulltext.v1.IndexRequest
	(*IndexResponse)(nil),          // 1: portunix.fulltext.v1.IndexResponse
	(*IndexBatchRequest)(nil),      // 2: portunix.fulltext.v1.IndexBatchRequest
	(*IndexBatchResponse)(nil),     // 3: portunix.fulltext.v1.IndexBatchResponse
	(*DeleteDocumentRequest)(nil),  // 4: portunix.fulltext.v1.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil), // 5: portunix.fulltext.v1.DeleteDocumentResponse
	(*SearchRequest)(nil),          // 6: portunix.fulltext.v1.SearchRequest
	(*SearchResult)(nil),           // 7: portunix.fulltext.v1.SearchResult
	(*SearchResponse)(nil),         // 8: portunix.fulltext.v1.SearchResponse
	(*GetStatsRequest)(nil),        // 9: portunix.fulltext.v1.GetStatsRequest
	(*GetStatsResponse)(nil),       // 10: portunix.fulltext.v1.GetStatsResponse
	(*EnsureIndexRequest)(nil),     // 11: portunix.fulltext.v1.EnsureIndexRequest
	(*EnsureIndexResponse)(nil),    // 12: portunix.fulltext.v1.EnsureIndexResponse
	(*DeleteIndexRequest)(nil),     // 13: portunix.fulltext.v1.DeleteIndexRequest
	(*DeleteIndexResponse)(nil),    // 14: portunix.fulltext.v1.DeleteIndexResponse
	(*HealthCheckRequest)(nil),     // 15: portunix.fulltext.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 16: portunix.fulltext.v1.HealthCheckResponse
	nil,                            // 17: portunix.fulltext.v1.IndexRequest.MetadataEntry
	nil,                            // 18: portunix.fulltext.v1.SearchRequest.FiltersEntry
	nil,                            // 19: portunix.fulltext.v1.SearchResult.MetadataEntry
	nil,                            // 20: portunix.fulltext.v1.GetStatsResponse.IndicesEntry
	nil,                            // 21: portunix.fulltext.v1.EnsureIndexRequest.SettingsEntry
}
var file_src_helpers_ptx_trace_proto_fulltext_proto_depIdxs = []int32{
	17, // 0: portunix.fulltext.v1.IndexRequest.metadata:type_name -> portunix.fulltext.v1.IndexRequest.MetadataEntry
	0,  // 1: portunix.fulltext.v1.IndexBatchRequest.documents:type_name -> portunix.fulltext.v1.IndexRequest
	18, // 2: portunix.fulltext.v1.SearchRequest.filters:type_name -> portunix.fulltext.v1.SearchRequest.FiltersEntry
	19, // 3: portunix.fulltext.v1.SearchResult.metadata:type_name -> portunix.fulltext.v1.SearchResult.MetadataEntry
	7,  // 4: portunix.fulltext.v1.SearchResponse.results:type_name -> portunix.fulltext.v1.SearchResult
	20, // 5: portunix.fulltext.v1.GetStatsResponse.indices:type_name -> portunix.fulltext.v1.GetStatsResponse.IndicesEntry
	21, // 6: portunix.fulltext.v1.EnsureIndexRequest.settings:type_name -> portunix.fulltext.v1.EnsureIndexRequest.SettingsEntry
	0,  // 7: portunix.fulltext.v1.FulltextService.IndexDocument:input_type -> portunix.fulltext.v1.IndexRequest
	2,  // 8: portunix.fulltext.v1.FulltextService.IndexBatch:input_type -> portunix.fulltext.v1.IndexBatchRequest
	4,  // 9: portunix.fulltext.v1.FulltextService.DeleteDocument:input_type -> portunix.fulltext.v1.DeleteDocumentRequest
	6,  // 10: portunix.fulltext.v1.FulltextService.Search:input_type -> portunix.fulltext.v1.SearchRequest
	9,  // 11: portunix.fulltext.v1.FulltextService.GetStats:input_type -> portunix.fulltext.v1.GetStatsRequest
	11, // 12: portunix.fulltext.v1.FulltextService.EnsureIndex:input_type -> portunix.fulltext.v1.EnsureIndexRequest
	13, // 13: portunix.fulltext.v1.FulltextService.DeleteIndex:input_type -> portunix.fulltext.v1.DeleteIndexRequest
	15, // 14: portunix.fulltext.v1.FulltextService.HealthCheck:input_type -> portunix.fulltext.v1.HealthCheckRequest
	1,  // 15: portunix.fulltext.v1.FulltextService.IndexDocument:output_type -> portunix.fulltext.v1.IndexResponse
	3,  // 16: portunix.fulltext.v1.FulltextService.IndexBatch:output_type -> portunix.fulltext.v1.IndexBatchResponse
	5,  // 17: portunix.fulltext.v1.FulltextService.DeleteDocument:output_type -> portunix.fulltext.v1.DeleteDocumentResponse
	8,  // 18: portunix.fulltext.v1.FulltextService.Search:output_type -> portunix.fulltext.v1.SearchResponse
	10, // 19: portunix.fulltext.v1.FulltextService.GetStats:output_type -> portunix.fulltext.v1.GetStatsResponse
	12, // 20: portunix.fulltext.v1.FulltextService.EnsureIndex:output_type -> portunix.fulltext.v1.EnsureIndexResponse
	14, // 21: portunix.fulltext.v1.FulltextService.DeleteIndex:output_type -> portunix.fulltext.v1.DeleteIndexResponse
	16, // 22: portunix.fulltext.v1.FulltextService.HealthCheck:output_type -> portunix.fulltext.v1.HealthCheckResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_src_helpers_ptx_trace_proto_fulltext_proto_init() }
func file_src_helpers_ptx_trace_proto_fulltext_proto_init() {
	if File_src_helpers_ptx_trace_proto_fulltext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_helpers_ptx_trace_proto_fulltext_proto_rawDesc), len(file_src_helpers_ptx_trace_proto_fulltext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_helpers_ptx_trace_proto_fulltext_proto_goTypes,
		DependencyIndexes: file_src_helpers_ptx_trace_proto_fulltext_proto_depIdxs,
		MessageInfos:      file_src_helpers_ptx_trace_proto_fulltext_proto_msgTypes,
	}.Build()
	File_src_helpers_ptx_trace_proto_fulltext_proto = out.File
	file_src_helpers_ptx_trace_proto_fulltext_proto_goTypes = nil
	file_src_helpers_ptx_trace_proto_fulltext_proto_depIdxs = nil
}
