// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: src/helpers/ptx-trace/proto/fulltext.proto

package fulltext

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FulltextService_IndexDocument_FullMethodName  = "/portunix.fulltext.v1.FulltextService/IndexDocument"
	FulltextService_IndexBatch_FullMethodName     = "/portunix.fulltext.v1.FulltextService/IndexBatch"
	FulltextService_DeleteDocument_FullMethodName = "/portunix.fulltext.v1.FulltextService/DeleteDocument"
	FulltextService_Search_FullMethodName         = "/portunix.fulltext.v1.FulltextService/Search"
	FulltextService_GetStats_FullMethodName       = "/portunix.fulltext.v1.FulltextService/GetStats"
	FulltextService_EnsureIndex_FullMethodName    = "/portunix.fulltext.v1.FulltextService/EnsureIndex"
	FulltextService_DeleteIndex_FullMethodName    = "/portunix.fulltext.v1.FulltextService/DeleteIndex"
	FulltextService_HealthCheck_FullMethodName    = "/portunix.fulltext.v1.FulltextService/HealthCheck"
)

// FulltextServiceClient is the client API for FulltextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FulltextService defines the gRPC interface for fulltext search operations
// This is the client-side definition for communicating with the fulltext plugin
type FulltextServiceClient interface {
	// Document indexing
	IndexDocument(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	IndexBatch(ctx context.Context, in *IndexBatchRequest, opts ...grpc.CallOption) (*IndexBatchResponse, error)
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	// Search
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Index management
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	EnsureIndex(ctx context.Context, in *EnsureIndexRequest, opts ...grpc.CallOption) (*EnsureIndexResponse, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error)
	// Health
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type fulltextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFulltextServiceClient(cc grpc.ClientConnInterface) FulltextServiceClient {
	return &fulltextServiceClient{cc}
}

func (c *fulltextServiceClient) IndexDocument(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, FulltextService_IndexDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulltextServiceClient) IndexBatch(ctx context.Context, in *IndexBatchRequest, opts ...grpc.CallOption) (*IndexBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexBatchResponse)
	err := c.cc.Invoke(ctx, FulltextService_IndexBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulltextServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, FulltextService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulltextServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, FulltextService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulltextServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, FulltextService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulltextServiceClient) EnsureIndex(ctx context.Context, in *EnsureIndexRequest, opts ...grpc.CallOption) (*EnsureIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureIndexResponse)
	err := c.cc.Invoke(ctx, FulltextService_EnsureIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulltextServiceClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...grpc.CallOption) (*DeleteIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIndexResponse)
	err := c.cc.Invoke(ctx, FulltextService_DeleteIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulltextServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, FulltextService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FulltextServiceServer is the server API for FulltextService service.
// All implementations must embed UnimplementedFulltextServiceServer
// for forward compatibility.
//
// FulltextService defines the gRPC interface for fulltext search operations
// This is the client-side definition for communicating with the fulltext plugin
type FulltextServiceServer interface {
	// Document indexing
	IndexDocument(context.Context, *IndexRequest) (*IndexResponse, error)
	IndexBatch(context.Context, *IndexBatchRequest) (*IndexBatchResponse, error)
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	// Search
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Index management
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	EnsureIndex(context.Context, *EnsureIndexRequest) (*EnsureIndexResponse, error)
	DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error)
	// Health
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedFulltextServiceServer()
}

// UnimplementedFulltextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFulltextServiceServer struct{}

func (UnimplementedFulltextServiceServer) IndexDocument(context.Context, *IndexRequest) (*IndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexDocument not implemented")
}
func (UnimplementedFulltextServiceServer) IndexBatch(context.Context, *IndexBatchRequest) (*IndexBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexBatch not implemented")
}
func (UnimplementedFulltextServiceServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedFulltextServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedFulltextServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedFulltextServiceServer) EnsureIndex(context.Context, *EnsureIndexRequest) (*EnsureIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureIndex not implemented")
}
func (UnimplementedFulltextServiceServer) DeleteIndex(context.Context, *DeleteIndexRequest) (*DeleteIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIndex not implemented")
}
func (UnimplementedFulltextServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFulltextServiceServer) mustEmbedUnimplementedFulltextServiceServer() {}
func (UnimplementedFulltextServiceServer) testEmbeddedByValue()                         {}

// UnsafeFulltextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FulltextServiceServer will
// result in compilation errors.
type UnsafeFulltextServiceServer interface {
	mustEmbedUnimplementedFulltextServiceServer()
}

func RegisterFulltextServiceServer(s grpc.ServiceRegistrar, srv FulltextServiceServer) {
	// If the following call pancis, it indicates UnimplementedFulltextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FulltextService_ServiceDesc, srv)
}

func _FulltextService_IndexDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulltextServiceServer).IndexDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulltextService_IndexDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulltextServiceServer).IndexDocument(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulltextService_IndexBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulltextServiceServer).IndexBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulltextService_IndexBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulltextServiceServer).IndexBatch(ctx, req.(*IndexBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulltextService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulltextServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulltextService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulltextServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulltextService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulltextServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulltextService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulltextServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulltextService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulltextServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulltextService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulltextServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulltextService_EnsureIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulltextServiceServer).EnsureIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulltextService_EnsureIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulltextServiceServer).EnsureIndex(ctx, req.(*EnsureIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulltextService_DeleteIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulltextServiceServer).DeleteIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulltextService_DeleteIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulltextServiceServer).DeleteIndex(ctx, req.(*DeleteIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulltextService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulltextServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FulltextService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulltextServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FulltextService_ServiceDesc is the grpc.ServiceDesc for FulltextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FulltextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portunix.fulltext.v1.FulltextService",
	HandlerType: (*FulltextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexDocument",
			Handler:    _FulltextService_IndexDocument_Handler,
		},
		{
			MethodName: "IndexBatch",
			Handler:    _FulltextService_IndexBatch_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _FulltextService_DeleteDocument_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _FulltextService_Search_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _FulltextService_GetStats_Handler,
		},
		{
			MethodName: "EnsureIndex",
			Handler:    _FulltextService_EnsureIndex_Handler,
		},
		{
			MethodName: "DeleteIndex",
			Handler:    _FulltextService_DeleteIndex_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _FulltextService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/helpers/ptx-trace/proto/fulltext.proto",
}
