/*
 *  This file is part of CassandraGargoyle Community Project
 *  Licensed under the MIT License - see LICENSE file for details
 */
package cmd

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"portunix.ai/portunix/src/helpers/ptx-specpm/internal/integration"
	"portunix.ai/portunix/src/helpers/ptx-specpm/internal/kit"
	"portunix.ai/portunix/src/helpers/ptx-specpm/internal/kitjson"
	"portunix.ai/portunix/src/helpers/ptx-specpm/internal/profiles"
	"portunix.ai/portunix/src/helpers/ptx-specpm/internal/scaffold"
)

var (
	initFlagHere               bool
	initFlagForce              bool
	initFlagIntegration        string
	initFlagIntegrationOptions string
	initFlagProfile            string
	initFlagSource             string
	initFlagRef                string
	initFlagIgnoreAgentTools   bool
	initFlagProjectID          string
)

var initCmd = &cobra.Command{
	Use:   "init [PROJECT_NAME|.]",
	Short: "Bootstrap a project with the spec-kit-pm scaffold",
	Long: `init bootstraps the spec-kit-pm scaffold in a project directory.

Forms:
  ptx-specpm init <PROJECT_NAME>     Create new directory and scaffold inside it
  ptx-specpm init .                  Initialise in the current directory
  ptx-specpm init --here             Same as 'init .'

The scaffold has two roots (per ADR-040):
  .specpm/                Kit cache — regenerated by init / upgrade
  specs/project/<id>/     User artifacts — never overwritten by re-runs

Default --source is 'git': the kit is shallow-cloned from upstream at the
pinned ref into ~/.cache/portunix/specpm/<ref>/ on the first run; later
runs read from cache. For air-gapped operation use --source <path> against
a vendored fork.`,
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

func init() {
	f := initCmd.Flags()
	f.BoolVar(&initFlagHere, "here", false, "Initialise in the current directory")
	f.BoolVar(&initFlagForce, "force", false, "Overwrite scaffold files (never user artifacts)")
	f.StringVar(&initFlagIntegration, "integration", "", "AI agent integration target (e.g. 'claude')")
	f.StringVar(&initFlagIntegrationOptions, "integration-options", "", `Driver-specific options (e.g. --integration-options="--skills")`)
	f.StringVar(&initFlagProfile, "profile", "", "Apply a profile bundled with the kit or installed under .specpm/profiles/")
	f.StringVar(&initFlagSource, "source", "git", "Kit source mode: 'git' (default) or absolute filesystem path")
	f.StringVar(&initFlagRef, "ref", "", "Override pinned ref (with --source git); default = DefaultPinnedRef")
	f.BoolVar(&initFlagIgnoreAgentTools, "ignore-agent-tools", false, "Skip detection of installed agent CLIs")
	f.StringVar(&initFlagProjectID, "project-id", "", "Project ID under specs/project/<id>/ (default: derived from target dir name)")
}

func runInit(cmd *cobra.Command, args []string) error {
	target, projectName, err := resolveTarget(args)
	if err != nil {
		return err
	}

	projectID := initFlagProjectID
	if projectID == "" {
		projectID = sanitizeProjectID(projectName)
	}

	provider, ref, err := selectKitProvider()
	if err != nil {
		return err
	}

	kitDir, fromCache, err := provider.Fetch()
	if err != nil {
		return fmt.Errorf("fetch kit: %w", err)
	}

	scaffoldOpts := scaffold.Options{
		TargetDir: target,
		KitDir:    kitDir,
		ProjectID: projectID,
		Force:     initFlagForce,
	}
	scaffoldResult, err := scaffold.Write(scaffoldOpts)
	if err != nil {
		return fmt.Errorf("write scaffold: %w", err)
	}

	// Profile resolution (Phase 1: existence check + record in kit.json).
	resolvedProfile := ""
	if initFlagProfile != "" {
		resolvedProfile, err = profiles.Resolve(target, initFlagProfile)
		if err != nil {
			return fmt.Errorf("profile %q: %w", initFlagProfile, err)
		}
	}

	// Integration driver (Phase 1: claude only).
	var integrationResult *integration.RenderResult
	if initFlagIntegration != "" {
		driver, ok := integration.Lookup(initFlagIntegration)
		if !ok {
			return fmt.Errorf("integration %q is not supported in this build (run 'integration list')", initFlagIntegration)
		}
		opts := integration.RenderOptions{
			TargetDir:           target,
			Skills:              parseSkillsOption(initFlagIntegrationOptions),
			IgnoreAgentTools:    initFlagIgnoreAgentTools,
			GovernanceIncludeFn: scaffold.AugmentClaudeMD,
		}
		r, derr := driver.Render(opts)
		if derr != nil {
			return fmt.Errorf("render %s integration: %w", driver.Name(), derr)
		}
		integrationResult = r
	}

	// Persist .specpm/kit.json so 'check' and 'upgrade' know what was used.
	manifest := kitjson.Manifest{
		Source:      initFlagSource,
		Ref:         ref,
		Profile:     resolvedProfile,
		Integration: initFlagIntegration,
		Skills:      parseSkillsOption(initFlagIntegrationOptions),
	}
	if err := kitjson.Write(filepath.Join(target, ".specpm", "kit.json"), manifest); err != nil {
		return fmt.Errorf("write kit.json: %w", err)
	}

	printInitSummary(target, projectID, ref, fromCache, scaffoldResult, integrationResult, resolvedProfile)
	return nil
}

func resolveTarget(args []string) (target, projectName string, err error) {
	if initFlagHere && len(args) > 0 && args[0] != "." {
		return "", "", errors.New("--here is incompatible with a positional PROJECT_NAME")
	}
	cwd, _ := os.Getwd()
	switch {
	case initFlagHere || (len(args) == 1 && args[0] == "."):
		target = cwd
		projectName = filepath.Base(cwd)
	case len(args) == 1:
		name := args[0]
		if filepath.IsAbs(name) {
			target = name
		} else {
			target = filepath.Join(cwd, name)
		}
		projectName = filepath.Base(target)
		if err := os.MkdirAll(target, 0o755); err != nil {
			return "", "", fmt.Errorf("create %q: %w", target, err)
		}
	default:
		return "", "", errors.New("missing PROJECT_NAME (use 'ptx-specpm init <name>' or 'init --here')")
	}
	return target, projectName, nil
}

func selectKitProvider() (kit.Provider, string, error) {
	switch {
	case initFlagSource == "" || initFlagSource == "git":
		ref := initFlagRef
		if ref == "" {
			ref = kit.DefaultPinnedRef
		}
		return kit.NewGitProvider(kit.UpstreamURL, ref), ref, nil
	case filepath.IsAbs(initFlagSource):
		return kit.NewLocalPathProvider(initFlagSource), "(local path)", nil
	default:
		// Treat any non-empty, non-"git" value as a relative path.
		abs, err := filepath.Abs(initFlagSource)
		if err != nil {
			return nil, "", fmt.Errorf("resolve --source path: %w", err)
		}
		return kit.NewLocalPathProvider(abs), "(local path)", nil
	}
}

// parseSkillsOption recognises the --integration-options="--skills" form.
// Other forms are reserved for future drivers.
func parseSkillsOption(raw string) bool {
	if raw == "" {
		return false
	}
	for _, piece := range strings.Split(raw, ",") {
		if strings.TrimSpace(piece) == "--skills" {
			return true
		}
	}
	return false
}

// sanitizeProjectID maps an arbitrary project name to a filesystem-safe id.
func sanitizeProjectID(name string) string {
	name = strings.TrimSpace(name)
	if name == "" || name == "." {
		return "default"
	}
	var b strings.Builder
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '_' || r == '.':
			b.WriteRune('-')
		case r == ' ':
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "default"
	}
	return out
}

func printInitSummary(target, projectID, ref string, fromCache bool, sc *scaffold.Result, ir *integration.RenderResult, profile string) {
	fmt.Printf("%s init complete\n", displayName)
	fmt.Println("==============================")
	fmt.Printf("Target              : %s\n", target)
	fmt.Printf("Project ID          : %s\n", projectID)
	fmt.Printf("Kit source          : %s\n", initFlagSource)
	fmt.Printf("Kit ref             : %s\n", ref)
	if initFlagSource == "" || initFlagSource == "git" {
		if fromCache {
			fmt.Println("Cache               : hit (offline)")
		} else {
			fmt.Println("Cache               : miss (cloned upstream, populated cache)")
		}
	}
	if profile != "" {
		fmt.Printf("Profile             : %s\n", profile)
	}
	if sc != nil {
		fmt.Printf("Kit cache root      : %s\n", filepath.Join(target, ".specpm"))
		fmt.Printf("Artifacts root      : %s\n", filepath.Join(target, "specs", "project", projectID))
		if sc.SkippedNoOp {
			fmt.Println("Re-run              : no-op (no scaffold changes; user artifacts untouched)")
		}
	}
	if ir != nil {
		fmt.Printf("Integration         : %s (%s)\n", ir.AgentName, ir.Mode)
		for _, p := range ir.WrittenPaths {
			fmt.Printf("  + %s\n", p)
		}
	}
	fmt.Println()
	fmt.Println("Next step: open the project in your AI agent and run /specpm.init to draft the Charter.")
}
