#!/usr/bin/env python3
"""
Portunix Local File Server
Serves Portunix binary and installation scripts for VMs and containers
"""

import http.server
import socketserver
import os
import sys
import socket
import argparse
from pathlib import Path

# Configuration
DEFAULT_PORT = 8080

# Colors for output
class Colors:
    RED = '\033[0;31m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    BLUE = '\033[0;34m'
    NC = '\033[0m'  # No Color

def print_info(message):
    print(f"{Colors.BLUE}ℹ️  {message}{Colors.NC}")

def print_success(message):
    print(f"{Colors.GREEN}✅ {message}{Colors.NC}")

def print_warning(message):
    print(f"{Colors.YELLOW}⚠️  {message}{Colors.NC}")

def print_error(message):
    print(f"{Colors.RED}❌ {message}{Colors.NC}")

def print_header():
    print()
    print(f"{Colors.BLUE}╔════════════════════════════════════════════════════════════════╗{Colors.NC}")
    print(f"{Colors.BLUE}║           Portunix Local File Server                          ║{Colors.NC}")
    print(f"{Colors.BLUE}╚════════════════════════════════════════════════════════════════╝{Colors.NC}")
    print()

def get_local_ip():
    """Get the local IP address"""
    try:
        # Create a socket to determine the local IP
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        try:
            return socket.gethostbyname(socket.gethostname())
        except:
            return "127.0.0.1"

def get_binary_info(serve_dir):
    """Get information about the Portunix binary"""
    binary_path = serve_dir / "portunix"

    if not binary_path.exists():
        return None

    size = binary_path.stat().st_size
    size_mb = size / (1024 * 1024)

    if size_mb < 1:
        size_str = f"{size / 1024:.1f} KB"
    else:
        size_str = f"{size_mb:.1f} MB"

    return {
        'path': binary_path,
        'size': size,
        'size_str': size_str,
        'exists': True
    }

def find_helpers(serve_dir):
    """Find all helper binaries in bin/ directory"""
    helpers = []
    bin_dir = serve_dir / "bin"

    if not bin_dir.exists():
        return helpers

    for file in bin_dir.iterdir():
        if file.is_file() and os.access(file, os.X_OK):
            helpers.append({
                'name': file.name,
                'path': file,
                'relative_path': f"bin/{file.name}"
            })

    return helpers

def create_install_script_linux(ip, port, serve_dir):
    """Create Linux installation script"""
    helpers = find_helpers(serve_dir)
    url = f"http://{ip}:{port}"

    script_content = f"""#!/bin/bash
# Portunix Auto-Install Script (Linux)
# Generated by file-server.py
# Server: {url}

set -e

# Colors
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

print_info() {{
    echo -e "${{BLUE}}ℹ️  $1${{NC}}"
}}

print_success() {{
    echo -e "${{GREEN}}✅ $1${{NC}}"
}}

print_error() {{
    echo -e "${{RED}}❌ $1${{NC}}"
}}

# Configuration
SERVER_URL="{url}"
INSTALL_DIR="/usr/local/bin"

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           Portunix Auto-Installer (Linux)                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

print_info "Downloading from: $SERVER_URL"
print_info "Installing to: $INSTALL_DIR"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "Please run as root (use sudo)"
    exit 1
fi

# Download main binary
print_info "Downloading Portunix main binary..."
if curl -fsSL -o "$INSTALL_DIR/portunix" "$SERVER_URL/portunix"; then
    chmod +x "$INSTALL_DIR/portunix"
    print_success "Portunix binary installed"
else
    print_error "Failed to download Portunix binary"
    exit 1
fi

# Download helpers
"""

    if helpers:
        script_content += "print_info \"Downloading helper binaries...\"\n"
        for helper in helpers:
            script_content += f"""
if curl -fsSL -o "$INSTALL_DIR/{helper['name']}" "$SERVER_URL/{helper['relative_path']}"; then
    chmod +x "$INSTALL_DIR/{helper['name']}"
    print_success "{helper['name']} installed"
else
    print_error "Failed to download {helper['name']}"
fi
"""

    script_content += """
echo ""
print_success "Installation completed!"
echo ""
print_info "Verify installation:"
echo "  portunix --version"
echo ""
"""

    # Save script
    script_path = serve_dir / "install-from-server.sh"
    script_path.write_text(script_content)
    os.chmod(script_path, 0o755)

    return script_path

def create_install_script_windows(ip, port, serve_dir):
    """Create Windows installation script"""
    helpers = find_helpers(serve_dir)
    url = f"http://{ip}:{port}"

    script_content = f"""# Portunix Auto-Install Script (Windows)
# Generated by file-server.py
# Server: {url}

$ErrorActionPreference = "Stop"

# Configuration
$ServerUrl = "{url}"
$InstallDir = "$env:ProgramFiles\\Portunix"

Write-Host ""
Write-Host "╔════════════════════════════════════════════════════════════════╗" -ForegroundColor Blue
Write-Host "║           Portunix Auto-Installer (Windows)                   ║" -ForegroundColor Blue
Write-Host "╚════════════════════════════════════════════════════════════════╝" -ForegroundColor Blue
Write-Host ""

Write-Host "ℹ️  Downloading from: $ServerUrl" -ForegroundColor Blue
Write-Host "ℹ️  Installing to: $InstallDir" -ForegroundColor Blue
Write-Host ""

# Check admin rights
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {{
    Write-Host "❌ Please run as Administrator" -ForegroundColor Red
    exit 1
}}

# Create install directory
if (-not (Test-Path $InstallDir)) {{
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}}

# Download main binary
Write-Host "ℹ️  Downloading Portunix main binary..." -ForegroundColor Blue
try {{
    Invoke-WebRequest -Uri "$ServerUrl/portunix" -OutFile "$InstallDir\\portunix.exe"
    Write-Host "✅ Portunix binary installed" -ForegroundColor Green
}} catch {{
    Write-Host "❌ Failed to download Portunix binary: $_" -ForegroundColor Red
    exit 1
}}

# Download helpers
"""

    if helpers:
        script_content += 'Write-Host "ℹ️  Downloading helper binaries..." -ForegroundColor Blue\n'
        for helper in helpers:
            helper_name = helper['name'] + (".exe" if not helper['name'].endswith('.exe') else "")
            script_content += f"""
try {{
    Invoke-WebRequest -Uri "$ServerUrl/{helper['relative_path']}" -OutFile "$InstallDir\\{helper_name}"
    Write-Host "✅ {helper['name']} installed" -ForegroundColor Green
}} catch {{
    Write-Host "❌ Failed to download {helper['name']}: $_" -ForegroundColor Red
}}
"""

    script_content += """
# Add to PATH if not already there
$currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
if ($currentPath -notlike "*$InstallDir*") {
    Write-Host "ℹ️  Adding to system PATH..." -ForegroundColor Blue
    [Environment]::SetEnvironmentVariable("Path", "$currentPath;$InstallDir", "Machine")
    Write-Host "✅ Added to PATH" -ForegroundColor Green
    Write-Host "⚠️  Restart your terminal to use Portunix" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "✅ Installation completed!" -ForegroundColor Green
Write-Host ""
Write-Host "ℹ️  Verify installation (after restarting terminal):" -ForegroundColor Blue
Write-Host "  portunix --version"
Write-Host ""
"""

    # Save script
    script_path = serve_dir / "install-from-server.ps1"
    script_path.write_text(script_content)

    return script_path

def print_usage_info(port, serve_dir):
    """Print usage information for clients"""
    ip = get_local_ip()
    url = f"http://{ip}:{port}"

    # Get helpers info
    helpers = find_helpers(serve_dir)
    helpers_info = f" + {len(helpers)} helpers" if helpers else ""

    print()
    print_success("File server is running!")
    print()
    print_info(f"Server URL: {url}")
    print_info(f"Serving directory: {serve_dir}")
    print_info(f"Binaries: portunix{helpers_info}")
    print()
    print(f"{Colors.GREEN}═══════════════════════════════════════════════════════════════{Colors.NC}")
    print(f"{Colors.GREEN}Auto-Install Scripts (RECOMMENDED):{Colors.NC}")
    print(f"{Colors.GREEN}═══════════════════════════════════════════════════════════════{Colors.NC}")
    print()
    print(f"{Colors.YELLOW}Linux (downloads portunix + all helpers):{Colors.NC}")
    print(f"  curl -fsSL {url}/install-from-server.sh | sudo bash")
    print(f"  wget -qO- {url}/install-from-server.sh | sudo bash")
    print()
    print(f"{Colors.YELLOW}Windows PowerShell (run as Administrator):{Colors.NC}")
    print(f"  Invoke-WebRequest -Uri {url}/install-from-server.ps1 -OutFile install.ps1")
    print(f"  .\\install.ps1")
    print()
    print(f"{Colors.GREEN}═══════════════════════════════════════════════════════════════{Colors.NC}")
    print(f"{Colors.GREEN}Manual Downloads:{Colors.NC}")
    print(f"{Colors.GREEN}═══════════════════════════════════════════════════════════════{Colors.NC}")
    print()
    print(f"{Colors.YELLOW}Portunix binary:{Colors.NC}")
    print(f"  curl -O {url}/portunix")
    print(f"  wget {url}/portunix")
    print()

    if helpers:
        print(f"{Colors.YELLOW}Helper binaries:{Colors.NC}")
        for helper in helpers:
            print(f"  curl -O {url}/{helper['relative_path']}")

    print()
    print(f"{Colors.GREEN}═══════════════════════════════════════════════════════════════{Colors.NC}")
    print()
    print_info(f"Browse all files: {url}/")
    print_info(f"Linux install script: {url}/install-from-server.sh")
    print_info(f"Windows install script: {url}/install-from-server.ps1")
    print()
    print_warning("Press Ctrl+C to stop the server")
    print()

class CustomHTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
    """Custom HTTP request handler with logging"""

    def log_message(self, format, *args):
        """Override to add colored logging"""
        client_ip = self.client_address[0]
        print(f"{Colors.BLUE}[{self.log_date_time_string()}]{Colors.NC} "
              f"{Colors.GREEN}{client_ip}{Colors.NC} - {format % args}")

def start_server(port, serve_dir):
    """Start the HTTP server"""

    # Change to serve directory
    os.chdir(serve_dir)

    # Check if binary exists
    binary_info = get_binary_info(serve_dir)
    if binary_info and binary_info['exists']:
        print_success(f"Portunix binary found ({binary_info['size_str']})")
    else:
        print_warning("Portunix binary not found - build it first with 'make build'")

    # Get IP address
    ip = get_local_ip()

    # Create installation scripts
    print_info("Generating installation scripts...")
    try:
        linux_script = create_install_script_linux(ip, port, serve_dir)
        print_success(f"Linux script: {linux_script.name}")

        windows_script = create_install_script_windows(ip, port, serve_dir)
        print_success(f"Windows script: {windows_script.name}")
    except Exception as e:
        print_error(f"Failed to create install scripts: {e}")
        sys.exit(1)

    # Create server
    try:
        with socketserver.TCPServer(("", port), CustomHTTPRequestHandler) as httpd:
            httpd.allow_reuse_address = True

            print_usage_info(port, serve_dir)

            # Start serving
            httpd.serve_forever()

    except KeyboardInterrupt:
        print()
        print_info("Shutting down file server...")
        print_success("Server stopped")
        sys.exit(0)
    except PermissionError:
        print_error(f"Permission denied to bind to port {port}")
        print_info("Try using a port > 1024 or run with sudo")
        sys.exit(1)
    except OSError as e:
        if "Address already in use" in str(e):
            print_error(f"Port {port} is already in use")
            print_info("Try a different port with: --port <number>")
        else:
            print_error(f"Failed to start server: {e}")
        sys.exit(1)

def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description='Portunix Local File Server - Serve Portunix binary and scripts for VMs/containers'
    )
    parser.add_argument(
        '--port', '-p',
        type=int,
        default=DEFAULT_PORT,
        help=f'Port to serve on (default: {DEFAULT_PORT})'
    )
    parser.add_argument(
        '--dir', '-d',
        type=Path,
        default=None,
        help='Directory to serve (default: project root)'
    )

    args = parser.parse_args()

    # Determine serve directory
    if args.dir:
        serve_dir = args.dir.resolve()
    else:
        # Default to project root (parent of scripts directory)
        script_dir = Path(__file__).parent.resolve()
        serve_dir = script_dir.parent

    if not serve_dir.exists():
        print_error(f"Directory does not exist: {serve_dir}")
        sys.exit(1)

    print_header()
    print_info(f"Starting file server on port {args.port}...")
    print_info(f"Serving directory: {serve_dir}")
    print()

    start_server(args.port, serve_dir)

if __name__ == "__main__":
    main()
