// Copyright (c) CassandraGargoyle Community Project.
// Licensed under the MIT License - see LICENSE file for details.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: plugin_registry.proto

package pluginregistry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginRegistryService_ListPluginsForPlatform_FullMethodName = "/portunix.plugins.registry.v1.PluginRegistryService/ListPluginsForPlatform"
	PluginRegistryService_HealthCheck_FullMethodName            = "/portunix.plugins.registry.v1.PluginRegistryService/HealthCheck"
)

// PluginRegistryServiceClient is the client API for PluginRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginRegistryService is the ptx-side gRPC face of the local plugin registry.
// Hosting platforms (Synapse, Pack, Agent, ...) query this service to discover
// which installed Portunix plugins target them and retrieve each plugin's
// platform-specific registration payload.
//
// This service is served by the ptx-plugin-registry helper binary (issue #175,
// DEC-1 / DEC-2). It is distinct from PluginService in plugin.proto — that
// service is implemented by plugins (Portunix is the client) and cannot answer
// for the registry as a whole.
type PluginRegistryServiceClient interface {
	// ListPluginsForPlatform returns the subset of installed plugins whose
	// supported_platforms[] declares the requested platform. Optional SemVer
	// range matching and feature AND-filter are applied identically to the
	// CLI form (`ptx plugin list --platform=... --platform-version=... --feature=...`).
	ListPluginsForPlatform(ctx context.Context, in *ListPluginsForPlatformRequest, opts ...grpc.CallOption) (*ListPluginsForPlatformResponse, error)
	// HealthCheck is a lightweight liveness probe for the ptx-plugin-registry
	// helper. Callers use it to verify the daemon started before issuing the
	// first ListPluginsForPlatform call.
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type pluginRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginRegistryServiceClient(cc grpc.ClientConnInterface) PluginRegistryServiceClient {
	return &pluginRegistryServiceClient{cc}
}

func (c *pluginRegistryServiceClient) ListPluginsForPlatform(ctx context.Context, in *ListPluginsForPlatformRequest, opts ...grpc.CallOption) (*ListPluginsForPlatformResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPluginsForPlatformResponse)
	err := c.cc.Invoke(ctx, PluginRegistryService_ListPluginsForPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginRegistryServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PluginRegistryService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginRegistryServiceServer is the server API for PluginRegistryService service.
// All implementations must embed UnimplementedPluginRegistryServiceServer
// for forward compatibility.
//
// PluginRegistryService is the ptx-side gRPC face of the local plugin registry.
// Hosting platforms (Synapse, Pack, Agent, ...) query this service to discover
// which installed Portunix plugins target them and retrieve each plugin's
// platform-specific registration payload.
//
// This service is served by the ptx-plugin-registry helper binary (issue #175,
// DEC-1 / DEC-2). It is distinct from PluginService in plugin.proto — that
// service is implemented by plugins (Portunix is the client) and cannot answer
// for the registry as a whole.
type PluginRegistryServiceServer interface {
	// ListPluginsForPlatform returns the subset of installed plugins whose
	// supported_platforms[] declares the requested platform. Optional SemVer
	// range matching and feature AND-filter are applied identically to the
	// CLI form (`ptx plugin list --platform=... --platform-version=... --feature=...`).
	ListPluginsForPlatform(context.Context, *ListPluginsForPlatformRequest) (*ListPluginsForPlatformResponse, error)
	// HealthCheck is a lightweight liveness probe for the ptx-plugin-registry
	// helper. Callers use it to verify the daemon started before issuing the
	// first ListPluginsForPlatform call.
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedPluginRegistryServiceServer()
}

// UnimplementedPluginRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginRegistryServiceServer struct{}

func (UnimplementedPluginRegistryServiceServer) ListPluginsForPlatform(context.Context, *ListPluginsForPlatformRequest) (*ListPluginsForPlatformResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPluginsForPlatform not implemented")
}
func (UnimplementedPluginRegistryServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginRegistryServiceServer) mustEmbedUnimplementedPluginRegistryServiceServer() {}
func (UnimplementedPluginRegistryServiceServer) testEmbeddedByValue()                               {}

// UnsafePluginRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginRegistryServiceServer will
// result in compilation errors.
type UnsafePluginRegistryServiceServer interface {
	mustEmbedUnimplementedPluginRegistryServiceServer()
}

func RegisterPluginRegistryServiceServer(s grpc.ServiceRegistrar, srv PluginRegistryServiceServer) {
	// If the following call pancis, it indicates UnimplementedPluginRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginRegistryService_ServiceDesc, srv)
}

func _PluginRegistryService_ListPluginsForPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsForPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServiceServer).ListPluginsForPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRegistryService_ListPluginsForPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServiceServer).ListPluginsForPlatform(ctx, req.(*ListPluginsForPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginRegistryService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginRegistryServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginRegistryService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginRegistryServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginRegistryService_ServiceDesc is the grpc.ServiceDesc for PluginRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portunix.plugins.registry.v1.PluginRegistryService",
	HandlerType: (*PluginRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPluginsForPlatform",
			Handler:    _PluginRegistryService_ListPluginsForPlatform_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginRegistryService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin_registry.proto",
}
