// Copyright (c) CassandraGargoyle Community Project.
// Licensed under the MIT License - see LICENSE file for details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: plugin_registry.proto

package pluginregistry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListPluginsForPlatformRequest parameters.
type ListPluginsForPlatformRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical platform identifier (e.g. "synapse"). Required.
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// Platform SemVer; when set, a plugin matches only if its
	// supported_platforms[platform].min_version / max_version admit this
	// version. Inclusive on both bounds; empty bound = unbounded.
	PlatformVersion string `protobuf:"bytes,2,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	// Required capability tokens. Plugin must declare ALL listed features
	// (AND-filter). Empty list disables the filter.
	Features      []string `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsForPlatformRequest) Reset() {
	*x = ListPluginsForPlatformRequest{}
	mi := &file_plugin_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsForPlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsForPlatformRequest) ProtoMessage() {}

func (x *ListPluginsForPlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsForPlatformRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsForPlatformRequest) Descriptor() ([]byte, []int) {
	return file_plugin_registry_proto_rawDescGZIP(), []int{0}
}

func (x *ListPluginsForPlatformRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ListPluginsForPlatformRequest) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *ListPluginsForPlatformRequest) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

// ListPluginsForPlatformResponse envelope.
type ListPluginsForPlatformResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*MatchedPlugin       `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsForPlatformResponse) Reset() {
	*x = ListPluginsForPlatformResponse{}
	mi := &file_plugin_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsForPlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsForPlatformResponse) ProtoMessage() {}

func (x *ListPluginsForPlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsForPlatformResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsForPlatformResponse) Descriptor() ([]byte, []int) {
	return file_plugin_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ListPluginsForPlatformResponse) GetPlugins() []*MatchedPlugin {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// MatchedPlugin is one entry in the query result — plugin identity plus the
// resolved supported_platforms entry for the requested platform.
type MatchedPlugin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin identity. These mirror the plugin-manifest.schema.json shape.
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author      string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	License     string `protobuf:"bytes,5,opt,name=license,proto3" json:"license,omitempty"`
	// SemVer range the plugin declared for the requested platform. Either
	// field may be empty to indicate an unbounded side.
	MinVersion string `protobuf:"bytes,6,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MaxVersion string `protobuf:"bytes,7,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`
	// All capability tokens declared by the plugin for this platform.
	DeclaredFeatures []string `protobuf:"bytes,8,rep,name=declared_features,json=declaredFeatures,proto3" json:"declared_features,omitempty"`
	// Subset of the caller's requested features that the plugin declared.
	// When the request features list was empty, this field is empty.
	MatchedFeatures []string `protobuf:"bytes,9,rep,name=matched_features,json=matchedFeatures,proto3" json:"matched_features,omitempty"`
	// Opaque platform_payload from the plugin manifest. Carried as raw JSON
	// bytes to preserve byte-identical round-trip (DEC-7 / acceptance
	// criterion). Portunix does not interpret the content — the target
	// platform (e.g. Synapse) validates it against its own schema.
	PlatformPayloadJson []byte `protobuf:"bytes,10,opt,name=platform_payload_json,json=platformPayloadJson,proto3" json:"platform_payload_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MatchedPlugin) Reset() {
	*x = MatchedPlugin{}
	mi := &file_plugin_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedPlugin) ProtoMessage() {}

func (x *MatchedPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchedPlugin.ProtoReflect.Descriptor instead.
func (*MatchedPlugin) Descriptor() ([]byte, []int) {
	return file_plugin_registry_proto_rawDescGZIP(), []int{2}
}

func (x *MatchedPlugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MatchedPlugin) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MatchedPlugin) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MatchedPlugin) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MatchedPlugin) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *MatchedPlugin) GetMinVersion() string {
	if x != nil {
		return x.MinVersion
	}
	return ""
}

func (x *MatchedPlugin) GetMaxVersion() string {
	if x != nil {
		return x.MaxVersion
	}
	return ""
}

func (x *MatchedPlugin) GetDeclaredFeatures() []string {
	if x != nil {
		return x.DeclaredFeatures
	}
	return nil
}

func (x *MatchedPlugin) GetMatchedFeatures() []string {
	if x != nil {
		return x.MatchedFeatures
	}
	return nil
}

func (x *MatchedPlugin) GetPlatformPayloadJson() []byte {
	if x != nil {
		return x.PlatformPayloadJson
	}
	return nil
}

// HealthCheckRequest is an empty probe.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_plugin_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_plugin_registry_proto_rawDescGZIP(), []int{3}
}

// HealthCheckResponse reports daemon readiness and build version.
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_plugin_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_plugin_registry_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_plugin_registry_proto protoreflect.FileDescriptor

const file_plugin_registry_proto_rawDesc = "" +
	"\n" +
	"\x15plugin_registry.proto\x12\x1cportunix.plugins.registry.v1\"\x82\x01\n" +
	"\x1dListPluginsForPlatformRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12)\n" +
	"\x10platform_version\x18\x02 \x01(\tR\x0fplatformVersion\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\"g\n" +
	"\x1eListPluginsForPlatformResponse\x12E\n" +
	"\aplugins\x18\x01 \x03(\v2+.portunix.plugins.registry.v1.MatchedPluginR\aplugins\"\xdf\x02\n" +
	"\rMatchedPlugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x18\n" +
	"\alicense\x18\x05 \x01(\tR\alicense\x12\x1f\n" +
	"\vmin_version\x18\x06 \x01(\tR\n" +
	"minVersion\x12\x1f\n" +
	"\vmax_version\x18\a \x01(\tR\n" +
	"maxVersion\x12+\n" +
	"\x11declared_features\x18\b \x03(\tR\x10declaredFeatures\x12)\n" +
	"\x10matched_features\x18\t \x03(\tR\x0fmatchedFeatures\x122\n" +
	"\x15platform_payload_json\x18\n" +
	" \x01(\fR\x13platformPayloadJson\"\x14\n" +
	"\x12HealthCheckRequest\"a\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xa1\x02\n" +
	"\x15PluginRegistryService\x12\x93\x01\n" +
	"\x16ListPluginsForPlatform\x12;.portunix.plugins.registry.v1.ListPluginsForPlatformRequest\x1a<.portunix.plugins.registry.v1.ListPluginsForPlatformResponse\x12r\n" +
	"\vHealthCheck\x120.portunix.plugins.registry.v1.HealthCheckRequest\x1a1.portunix.plugins.registry.v1.HealthCheckResponseB.Z,portunix.ai/app/plugins/proto/pluginregistryb\x06proto3"

var (
	file_plugin_registry_proto_rawDescOnce sync.Once
	file_plugin_registry_proto_rawDescData []byte
)

func file_plugin_registry_proto_rawDescGZIP() []byte {
	file_plugin_registry_proto_rawDescOnce.Do(func() {
		file_plugin_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_registry_proto_rawDesc), len(file_plugin_registry_proto_rawDesc)))
	})
	return file_plugin_registry_proto_rawDescData
}

var file_plugin_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_registry_proto_goTypes = []any{
	(*ListPluginsForPlatformRequest)(nil),  // 0: portunix.plugins.registry.v1.ListPluginsForPlatformRequest
	(*ListPluginsForPlatformResponse)(nil), // 1: portunix.plugins.registry.v1.ListPluginsForPlatformResponse
	(*MatchedPlugin)(nil),                  // 2: portunix.plugins.registry.v1.MatchedPlugin
	(*HealthCheckRequest)(nil),             // 3: portunix.plugins.registry.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 4: portunix.plugins.registry.v1.HealthCheckResponse
}
var file_plugin_registry_proto_depIdxs = []int32{
	2, // 0: portunix.plugins.registry.v1.ListPluginsForPlatformResponse.plugins:type_name -> portunix.plugins.registry.v1.MatchedPlugin
	0, // 1: portunix.plugins.registry.v1.PluginRegistryService.ListPluginsForPlatform:input_type -> portunix.plugins.registry.v1.ListPluginsForPlatformRequest
	3, // 2: portunix.plugins.registry.v1.PluginRegistryService.HealthCheck:input_type -> portunix.plugins.registry.v1.HealthCheckRequest
	1, // 3: portunix.plugins.registry.v1.PluginRegistryService.ListPluginsForPlatform:output_type -> portunix.plugins.registry.v1.ListPluginsForPlatformResponse
	4, // 4: portunix.plugins.registry.v1.PluginRegistryService.HealthCheck:output_type -> portunix.plugins.registry.v1.HealthCheckResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_registry_proto_init() }
func file_plugin_registry_proto_init() {
	if File_plugin_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_registry_proto_rawDesc), len(file_plugin_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_registry_proto_goTypes,
		DependencyIndexes: file_plugin_registry_proto_depIdxs,
		MessageInfos:      file_plugin_registry_proto_msgTypes,
	}.Build()
	File_plugin_registry_proto = out.File
	file_plugin_registry_proto_goTypes = nil
	file_plugin_registry_proto_depIdxs = nil
}
