name: go-plugin-template
version: 1.0.0
description: Template for Go-based Portunix plugins
author: Your Name
license: MIT

type: service
capabilities:
  - example-capability

runtime:
  language: go
  main: ./plugin
  port: 50051
  health_check_port: 50052
  metrics_port: 8080

dependencies:
  system: []
  plugins: []

permissions:
  filesystem:
    read: []
    write: []
  network:
    outbound: []
  system:
    execute: []

configuration:
  required: {}
  optional:
    log_level:
      type: string
      default: "info"
      description: "Logging level (debug, info, warn, error)"
    timeout:
      type: integer
      default: 30
      description: "Request timeout in seconds"

mcp:
  tools:
    - name: example_tool
      description: Example tool for demonstration
      parameters:
        input:
          type: string
          description: Input parameter for the tool